import { SudokuPuzzle, SudokuPuzzleBasic } from "./types";
import { makepuzzle, solvepuzzle, ratepuzzle } from "sudoku";

function convertSudokuPuzzle(regularPuzzle: number[]): SudokuPuzzle {
  const convertedPuzzle = initEmptyGrid();

  /*
    The puzzle generated by sudoku package is a 1-dimensional array of 81 values.
    An empty cell is marked with value `null`
  */

  let regularPuzzleIndex = 0;

  for (let col = 0; col < convertedPuzzle.length; col++) {
    for (let row = 0; row < convertedPuzzle[col].length; row++) {
      convertedPuzzle[col][row] =
        regularPuzzle[regularPuzzleIndex] === 0 ||
        regularPuzzle[regularPuzzleIndex] === null
          ? {
              value: 0,
              set: false,
              notes: [],
            }
          : {
              value: regularPuzzle[regularPuzzleIndex],
              set: true,
              notes: [],
            };

      regularPuzzleIndex++;
    }
  }

  return convertedPuzzle;
}

export function createSudokuPuzzle(): {
  puzzle: SudokuPuzzle;
  answer: SudokuPuzzle;
} {
  const rawPuzzle = makepuzzle();

  const puzzle = convertSudokuPuzzle(rawPuzzle);
  const answer = convertSudokuPuzzle(solvepuzzle(rawPuzzle));

  console.dir(puzzle);

  return { puzzle, answer };
}

export function deepCopy(puzzle: SudokuPuzzle): SudokuPuzzle {
  return JSON.parse(JSON.stringify(puzzle));
}

export function deepCopyBasic(puzzle: SudokuPuzzleBasic): SudokuPuzzleBasic {
  return JSON.parse(JSON.stringify(puzzle));
}

export default class SudokuController {
  rows: number;
  cols: number;
  grid: SudokuPuzzle;

  constructor(N: number) {
    this.rows = N;
    this.cols = N;
    this.grid = initEmptyGrid();
  }

  initEmptyGrid(): SudokuPuzzle {
    const puzzle = new Array(9);

    for (let i = 0; i < puzzle.length; i++) {
      puzzle[i] = new Array(9);
    }

    for (let col = 0; col < puzzle.length; col++) {
      for (let row = 0; row < puzzle[col].length; row++) {
        puzzle[col][row] = 0;
      }
    }

    return puzzle;
  }
}

/** Check if a SudokuPuzzle is valid */
export function isValidSudoku(
  puzzle: SudokuPuzzle,
  answer: SudokuPuzzle
): boolean {
  // TODO: Reimplement to hold a value that is equivalent to how many missing there are
  // Once that value is 0, only then should this function be called
  for (let col = 0; col < puzzle.length; col++) {
    for (let row = 0; row < puzzle[col].length; row++) {
      if (puzzle[col][row].value !== answer[col][row].value) {
        return false;
      }
    }
  }

  return true;
}

export function initEmptyGrid(): SudokuPuzzle {
  const puzzle = new Array(9);

  for (let i = 0; i < puzzle.length; i++) {
    puzzle[i] = new Array(9);
  }

  for (let col = 0; col < puzzle.length; col++) {
    for (let row = 0; row < puzzle[col].length; row++) {
      puzzle[col][row] = 0;
    }
  }

  return puzzle;
}
